### ISSUE TITLE
Temperature sensor

### ISSUE THREAD

**Issue by e-duards** [songzh96/homebridge-crestron#10]
I am experiencing an issue with a temperature sensor. If I add a temperature sensor to config, I get "this accessory is not responding message. Humidity sensor works just fine. I have tried with different values from Crestron side. Any ideas how to fix it?

**Comment by e-duards** [comment]
The question could be as well "Has anyone used plugin and Crestron module as-is with a temperature sensor?"

**Comment by e-duards** [comment]
In the terminal, I am repeatedly getting message "RETRY: TemperatureSensor:1:getCurrentTemperature:*"

**Comment by songzh96** [comment]
Hi

I also had this problem.
I used the latest version of the software to compile,
Therefore, you need to upgrade your host firmware.
These macros can be used very well.

Best Regards
Songzh

**Comment by the-white-wizard** [comment]
The issue is that the homebridge server is sending "TemperatureSensor:ID:getCurrentTemperature" and the Crestron module is looking for "TemperatureSensor:ID:getTempSensorCurrentTemperature" in order to send a response with the current temperature.

You can either modify index.js to send a request that matches the current .usp or you can modify the .usp to respond to the current request that the homebridge server issues. I did the latter, and it's working fine now.

Incidentally, I also modified index.js to parse the incoming value as a float, rather than an int, so that you can actually display non-integer values for temperature. You just need to remember to convert the int (XXXº) analog values on the Crestron side to decimal (XX.Xº), within the values that get passed on to the CmdBuilder function.

Hope that helps!

**Comment by songzh96** [comment]
> The issue is that the homebridge server is sending "TemperatureSensor:ID:getCurrentTemperature" and the Crestron module is looking for "TemperatureSensor:ID:getTempSensorCurrentTemperature" in order to send a response with the current temperature.
> 
> You can either modify index.js to send a request that matches the current .usp or you can modify the .usp to respond to the current request that the homebridge server issues. I did the latter, and it's working fine now.
> 
> Incidentally, I also modified index.js to parse the incoming value as a float, rather than an int, so that you can actually display non-integer values for temperature. You just need to remember to convert the int (XXXº) analog values on the Crestron side to decimal (XX.Xº), within the values that get passed on to the CmdBuilder function.
> 
> Hope that helps!

Thanks Fixed

**Comment by dnwilliams78** [comment]
[deleted - error on my side]
