### ISSUE TITLE
Crestron Authentication support

### ISSUE THREAD

**Issue by evgolsh** [songzh96/homebridge-crestron#12]
Hello, I'm trying to connect to my Crestron MC4-R, but it is failing because it requires authentication. I didn't find in the code support for passing password. Is there any chance you open source the SIMPL module or add authentication support?

**Comment by songzh96** [comment]
Hi
The plugin doesn't support MC4-R but support MC4

**Comment by evgolsh** [comment]
Is the MC4-R support is coming? Is there any major difference between MC4 and MC4-R?

**Comment by songzh96** [comment]
MC4-R is a host that supports Crestron OS3 and is a host of platform configuration type. Because it is closed programming, I cannot support it.

MC4 is a programming type host, because it is relatively open, so I can get data and connect the device to Homekit


About the detailed difference between the two, you can search in Google
